function [ FlippedModel, FlippedSourceLocation, FlippedReceiverLocation ] = FlipModel( Model, SourceNumber, ReceiverNumber )

DefaultLastLayerThickness = 2000;
ModelTotalDepth = sum( [ Model.Layers.Thickness(1:end-1), DefaultLastLayerThickness ] );

SourceLocation = double( Model.SourceLocation(:, SourceNumber) );
ReceiverLocation = double( Model.ReceiverLocation(:, ReceiverNumber ) );


FlippedLayers = struct( ...
    'Thickness', [ DefaultLastLayerThickness, Model.Layers.Thickness(end-1:-1:2), 0 ], ...
    'Vp', fliplr( Model.Layers.Vp ), ...
    'Vs', fliplr( Model.Layers.Vs ), ...
    'Density', fliplr( Model.Layers.Density ), ...
    'Qp', fliplr( Model.Layers.Qp ), ...
    'Qs', fliplr( Model.Layers.Qs ) );

FlippedSourceLocation = Points3D( [ SourceLocation(1); ...
                          SourceLocation(2); ...
                          ModelTotalDepth - SourceLocation(3) ] );
                      
FlippedReceiverLocation = Points3D( [ ReceiverLocation(1); ...
                            ReceiverLocation(2); ...
                            ModelTotalDepth - ReceiverLocation(3) ] );

FlippedSourceFrequency = Model.SourceFrequency(SourceNumber);

FlippedRecordingTimes = Model.RecordingTimes;

FlippedModel = LayeredElasticModel( ...
    'Layers', FlippedLayers, ...
    'SourceLocation', FlippedSourceLocation, ...
    'ReceiverLocation', FlippedReceiverLocation, ...
    'SourceFrequency', FlippedSourceFrequency, ...
    'RecordingTimes', FlippedRecordingTimes );
                        
                        
end