% 3-D Rotation Matrix About X, Y, Z
% Sang Min Han
% 07/10/2015

function R = rot_xyz(alpha, beta, gamma)
% 3-d rotation matrix that performs rotations alpha about x, beta about y,
% and gamma about z, respectively

R= [...
    cos(beta)*cos(gamma) ...
    cos(gamma)*sin(alpha)*sin(beta) - cos(alpha)*sin(gamma) ...
    cos(alpha)*cos(gamma)*sin(beta) + sin(alpha)*sin(gamma); ...
    
    cos(beta)*sin(gamma) ...
    cos(alpha)*cos(gamma) + sin(alpha)*sin(beta)*sin(gamma) ...
    -cos(gamma)*sin(alpha) + cos(alpha)*sin(beta)*sin(gamma); ...
    
    -sin(beta) ...
    cos(beta)*sin(alpha) ...
    cos(alpha)*cos(beta)...
    ];

end
