% 3-D Rotation Matrix About Z, Y, X
% Sang Min Han
% 07/10/2015

function R = rot_zyx(gamma, beta, alpha)
% 3-d rotation matrix that performs rotations gamma about z, beta about y,
% and alpha about x, respectively

R= [...
    cos(beta)*cos(gamma) ...
    -cos(beta)*sin(gamma) ...
    sin(beta); ...
    
    cos(alpha)*sin(gamma) + sin(alpha)*sin(beta)*cos(gamma) ...
    cos(alpha)*cos(gamma) - sin(alpha)*sin(beta)*sin(gamma) ...
    -sin(alpha)*cos(beta); ...
    
    sin(alpha)*sin(gamma) - cos(alpha)*sin(beta)*cos(gamma) ...
    sin(alpha)*cos(gamma) + cos(alpha)*sin(beta)*sin(gamma) ...
    cos(alpha)*cos(beta)...
    ];

end
