function ShowConfidenceRegion( gridX, gridY, pdf, confidenceLevel, varargin )

assert( isvector( gridX ) ...
    && isvector( gridY ) ...
    && ismatrix( pdf ) ...
    && isscalar( confidenceLevel ) ...
    && size( pdf, 1 ) == length( gridX ) ...
    && size( pdf, 2 ) == length( gridY ) ...
    && confidenceLevel >= 0 ...
    && confidenceLevel <= 1 );

contourLevel = FindConfidenceContourLevel( gridX, gridY, pdf, confidenceLevel );
singleContourLevel = [ contourLevel, contourLevel ]; 
% If contourLevel is an integer, then contour inteprets this value as the
% number of different contours to display. This way we ensure that a single
% contour level is displayed

contour( gridX, gridY, transpose( pdf ), singleContourLevel, varargin{:} );

end