function anglesTrue = TrueAngles( movingUra, source, time )

arrayPosition = movingUra.positionFcn(time);
rotationMatrix = RotationMatrix( ...
    movingUra.rotationXFcn(time), ...
    movingUra.rotationYFcn(time), ...
    movingUra.rotationZFcn(time) ...
    );
xRotated = rotationMatrix * [1;0;0];
yRotated = rotationMatrix * [0;1;0];

anglesTrue = [ ...
    pi/2 - AngleBetweenVectors3D(source.position - arrayPosition, xRotated ), ...
    pi/2 - AngleBetweenVectors3D(source.position - arrayPosition, yRotated )
    ];

end