function Matrix = RotationMatrix3D( RotationAxis, RotationAngle )

assert( numel( RotationAxis ) == 3 );
assert( numel( RotationAngle ) == 1 );

RotationAxis = RotationAxis / norm( RotationAxis );

Cosine = cos( RotationAngle );
Sine = sin( RotationAngle );
OneMinusCosine = 1 - Cosine;

Matrix = [ Cosine + RotationAxis(1) ^ 2 * OneMinusCosine, ...
           RotationAxis(1)*RotationAxis(2)*OneMinusCosine - RotationAxis(3)*Sine, ...
           RotationAxis(1)*RotationAxis(3)*OneMinusCosine+RotationAxis(2)*Sine ; ...
           ...
           RotationAxis(2)*RotationAxis(1)*OneMinusCosine + RotationAxis(3)*Sine, ...
           Cosine+RotationAxis(2)^2 * OneMinusCosine, ...
           RotationAxis(2)*RotationAxis(3)*OneMinusCosine-RotationAxis(1)*Sine; ...
           ...
           RotationAxis(3)*RotationAxis(1)*OneMinusCosine-RotationAxis(2)*Sine, ...
           RotationAxis(3)*RotationAxis(2)*OneMinusCosine + RotationAxis(1)*Sine, ...
           Cosine + RotationAxis(3)^2 * OneMinusCosine ];



end