function antennaPositions = GetAntennaPositions( ura, arrayPosition, uraRotation )

assert( isa( ura, 'UniformRectangularAntennaArray' ) );
assert( ...
    isvector( arrayPosition ) && ...
    isreal( arrayPosition ) && ...
    length( arrayPosition ) == 3 ...
    );
assert( ...
    ( ismatrix( uraRotation ) && isequal( size( uraRotation ), [3 3] ) ) || ...
    ( isvector( uraRotation ) && length( uraRotation ) == 3 ) ...
    );

if isvector( uraRotation )
    uraRotation = RotationMatrix( uraRotation(1), uraRotation(2), uraRotation(3) );
    % else uraRotation is a directly supplied rotation matrix
end

antennaPositions = reshape( ...
    uraRotation * [ ura.antennaGeometry(:,:) ; zeros( 1, ura.totalAntennas ) ] ...
    + repmat( ToColumn( arrayPosition ), [1 ura.totalAntennas] ), ...
    [3 ura.totalCols ura.totalRows] ...
    );

end